apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: {{ .Values.global.amdllm.reranker.service_name }}
  name: {{ .Values.global.amdllm.reranker.service_name }}
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.global.amdllm.reranker.service_name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/chatqna-default: "true"
        io.kompose.service: {{ .Values.global.amdllm.reranker.service_name }}
    spec:
      containers:
        - args:
            - --model-id
            - {{ .Values.global.amdllm.reranker.model }}
            - --port
            - "{{ .Values.global.amdllm.reranker.container_port }}"
          env:
            - name: {{ .Values.global.amdllm.secret.env_name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.global.amdllm.secret.key }}
                  name: {{ .Values.global.amdllm.secret.name }}
            - name: HOME
              value: /data
            {{- if .Values.global.amdllm.runtime_envs }}
            {{- range .Values.global.amdllm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.amdllm.image }}
          name: {{ .Values.global.amdllm.reranker.name }}-server
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: {{ .Values.global.amdllm.reranker.service_name }}-claim0
      restartPolicy: Always
      volumes:
        - name: {{ .Values.global.amdllm.reranker.service_name }}-claim0
          persistentVolumeClaim:
            claimName: {{ .Values.global.amdllm.reranker.service_name }}-claim0
