clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
    - open-cluster-management
    - vault
    - golang-external-secrets
    # TODO(SG): Create the AMD operator namespace (if needed)
    - amd-gpu-operator
    - openshift-kmm:
        operatorGroup: true
        targetNamespaces:
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces:
    - amd-llm

  subscriptions:
    kmm:
      name: kernel-module-management
      namespace: openshift-kmm
      channel: stable
      source: redhat-operators

    amd-ai:
      name: amd-gpu-operator
      namespace: amd-gpu-operator
      # TODO(SG): This is the ONLY channel available for this oeprator
      channel: alpha
      source: certified-operators

    rhods:
      name: rhods-operator
      namespace: redhat-ods-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      channel: stable

    rhsm:
      name: servicemeshoperator
      namespace: openshift-operators
      source: redhat-operators
      channel: stable

    rhs:
      name: serverless-operator
      namespace: openshift-operators
      source: redhat-operators
      channel: stable

  projects:
    - hub
    - openshift-kmm
    - amd-gpu-operator
    - redhat-ods-operator
    - amd-llm

  # Explicitly mention the cluster-state based overrides we plan to use for this pattern.
  # We can use self-referential variables because the chart calls the tpl function with these variables defined
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
  # sharedValueFiles is a flexible mechanism that will add the listed valuefiles to every app defined in the
  # applications section. We intend this to supplement and possibly even replace previous "magic" mechanisms, though
  # we do not at present have a target date for removal.
  #
  # To replicate the "classic" magic include structure, the clusterGroup would need all of these
  # sharedValueFiles, in this order:
  #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-{{ $.Values.global.clusterVersion }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.clusterPlatform }}-{{ $.Values.clusterGroup.name }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.clusterVersion }}-{{ $.Values.clusterGroup.name }}.yaml"
  #   - '/overrides/values-{{ $.Values.global.localClusterName }}.yaml'

  # This kind of variable substitution will work with any of the variables the Validated Patterns operator knows
  # about and sets, so this is also possible, for example:
  #   - '/overrides/values-{{ $.Values.global.hubClusterDomain }}.yaml'
  #   - '/overrides/values-{{ $.Values.global.localClusterDomain }}.yaml'

  applications:
    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets
    kmm:
      name: kmm
      namespace: openshift-kmm
      project: openshift-kmm
      path: charts/all/kmm
    openshift-data-foundations:
      name: odf
      namespace: openshift-storage
      project: hub
      path: charts/all/openshift-data-foundations
    # TODO(SG): What's the AMD equivalent
    # Will enable amd-ai charts once we've figured out what to add in the charts
#    amd-gpu-operator:
#      name: amd-ai
#      namespace: amd-gpu-operator
#      project: amd-gpu-operator
#      path: charts/all/amd-ai
#    habana-ai:
#      name: habana-ai
#      namespace: habana-ai-operator
#      project: habana-ai-operator
#      path: charts/all/habana-ai
    rhods-operator:
      name: rhods-operator
      namespace: redhat-ods-operator
      project: redhat-ods-operator
      path: charts/all/rhods-operator
    rhods-amd-addons:
      name: rhods-amd-addons
      namespace: redhat-ods-operator
      project: redhat-ods-operator
      path: charts/all/rhods-operator-amd-addons
    init-secret:
      name: init-secret
      namespace: amd-llm
      project: amd-llm
      path: charts/all/init-secret
    redis-vector-db:
      name: redis-vector-db
      namespace: amd-llm
      project: amd-llm
      path: charts/all/redis-vector-db
    amd-llm-init:
      name: amd-llm-init
      namespace: amd-llm
      project: amd-llm
      path: charts/all/amd-llm-init
      ignoreDifferences:
        - group: machineconfiguration.openshift.io
          kind: KubeletConfig
          name:
          jsonPointers:
            - /metadata/labels/argocd.argoproj.io~1instance
            - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    text-embeddings-inference:
      name: text-embeddings-inference
      namespace: amd-llm
      project: amd-llm
      path: charts/all/tei
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'
    retriever:
      name: retriever
      namespace: amd-llm
      project: amd-llm
      path: charts/all/retriever
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'
    reranking:
      name: reranking
      namespace: amd-llm
      project: amd-llm
      path: charts/all/reranking
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'
    llm:
      name: llm
      namespace: amd-llm
      project: amd-llm
      path: charts/all/llm
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'
    embedding:
      name: embedding
      namespace: amd-llm
      project: amd-llm
      path: charts/all/embedding
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'
    dataprep:
      name: dataprep
      namespace: amd-llm
      project: amd-llm
      path: charts/all/dataprep
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'
    chatqna-ui:
      name: chatqna-ui
      namespace: amd-llm
      project: amd-llm
      path: charts/all/chatqna-ui
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
            - '.spec.template.spec.initContainers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'
    chatqna-backend:
      name: chatqna-backend
      namespace: amd-llm
      project: amd-llm
      path: charts/all/chatqna-amd-backend
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jqPathExpressions:
            - '.spec.template.spec.containers[].image'
        - group: build.openshift.io
          kind: BuildConfig
          jqPathExpressions:
            - '.spec.paused'

  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs:
      - name: hello-world
        # ansible playbook to be run
        playbook: common/ansible/playbooks/hello-world/hello-world.yaml
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"

  managedClusterGroups:
    exampleRegion:
      name: group-one
      acmlabels:
        - name: clusterGroup
          value: group-one
      helmOverrides:
        - name: clusterGroup.isHubCluster
          value: false
          # Before enabling cluster provisioning, ensure AWS and/or Azure
          #   credentials and OCP pull secrets are defined in Vault.
          #   See values-secret.yaml.template
          #
          #clusterPools:
          #  exampleAWSPool:
          #    name: aws-ap
          #    openshiftVersion: 4.10.18
          #    baseDomain: blueprints.rhecoeng.com
          #    platform:
          #      aws:
          #        region: ap-southeast-2
          #    clusters:
          #    - One
          #
          #  exampleAzurePool:
          #    name: azure-us
          #    openshiftVersion: 4.10.18
          #    baseDomain: blueprints.rhecoeng.com
          #    platform:
          #      azure:
          #        baseDomainResourceGroupName: dojo-dns-zones
          #        region: eastus
          #    clusters:
          #    - Two
          #    - Three
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
