{{- if .Values.global.build.enabled }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.global.amdllm.service_name }}
  namespace: {{ .Values.global.amdllm.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "{{ .Values.global.amdllm.service_name }}:latest"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    contextDir: ChatQnA
    git:
      ref: {{ .Values.global.amdllm.git_ref }}
      uri: {{ .Values.global.amdllm.git_repo_uri }}
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.global.amdllm.docker_file_Path }}
      {{- if .Values.global.amdllm.build_envs }}
      env:
      {{- range .Values.global.amdllm.build_envs }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}

  triggers:
    - type: ConfigChange
{{- end }}
