apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.global.amdllm.service_name }}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Values.global.amdllm.service_name }}-server\")].image"}]'
  labels:
    io.kompose.service: {{ .Values.global.amdllm.service_name }}
  name: llm
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.global.amdllm.service_name }}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/chatqna-default: "true"
        io.kompose.service: {{ .Values.global.amdllm.service_name }}
    spec:
      containers:
        - env:
            {{- if .Values.global.amdllm.env }}
            {{- range .Values.global.amdllm.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
            {{- if .Values.global.amdllm.secret_env }}
            {{- range .Values.global.amdllm.secret_env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  key: {{ .secret.key }}
                  name: {{ .secret.name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}

            {{- if .Values.global.amdllm.runtime_envs }}
            {{- range .Values.global.amdllm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.amdllm.image }}
          name: {{ .Values.global.amdllm.service_name }}-server
          ports:
            - containerPort: {{ .Values.global.amdllm.container_port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.global.amdllm.volume.tmp.name }}
              mountPath: {{ .Values.global.amdllm.volume.tmp.path }}
            - name: {{ .Values.global.amdllm.volume.rhoai_ca.name }}
              mountPath: {{ .Values.global.amdllm.volume.rhoai_ca.path }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.global.amdllm.volume.tmp.name }}
          emptyDir: {}
        - name: {{ .Values.global.amdllm.volume.rhoai_ca.name }}
          secret:
            secretName: {{ .Values.global.amdllm.secret.rhoai_ca.name }}
            defaultMode: 420
