---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.global.amdllm.service_name }}
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  host: megaservice-{{ .Values.global.amdllm.namespace }}.apps.{{ .Values.global.clusterDomain }}
  path: {{ .Values.global.amdllm.route_path }}
  port:
    targetPort: {{ .Values.global.amdllm.service_port }}
  tls:
    termination: edge
  to:
    name: {{ .Values.global.amdllm.service_name }}
---
