apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: amd-gpu-operator-nfd-instance
  namespace: {{ .Values.nfd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  operand:
    {{ if eq $.Values.global.clusterVersion "4.15" }}
    image: {{ .Values.nfd.images.v415 }}
    {{ else if eq $.Values.global.clusterVersion "4.16" }}
    image: {{ .Values.nfd.images.v416 }}
    {{ else if eq $.Values.global.clusterVersion "4.17" }}
    image: {{ .Values.nfd.images.v417 }}
    {{ else if eq $.Values.global.clusterVersion "4.18" }}
    image: {{ .Values.nfd.images.v418 }}
    {{ else }}
    image: undefined-ocp-version-match
    {{ end }}
    imagePullPolicy: IfNotPresent
    servicePort: 12000
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
      sources:
        pci:
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
          deviceLabelFields:
            - "vendor"
            - "device"
        custom:
        - name: amd-gpu
          labels:
            feature.node.kubernetes.io/amd-gpu: "true"
          matchAny:
            - matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    vendor: {op: In, value: ["1002"]}
                    device: {op: In, value: [
                      "74a0", # MI300A
                      "74a1", # MI300X
                      "740f", # MI210
                      "7408", # MI250X
                      "740c", # MI250/MI250X
                      "738c", # MI100
                      "738e",  # MI100
                      "7362"  # TODO - [JARY] test to see if it'll pick up on ec2 radeon / g4ad instances
                    ]}