apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"{{ .Values.global.amdllm.service_name }}:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"{{ .Values.global.amdllm.service_name }}-server\")].image"}]'
  labels:
    io.kompose.service: {{ .Values.global.amdllm.service_name }}
  name: {{ .Values.global.amdllm.service_name }}
  namespace: {{ .Values.global.amdllm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.global.amdllm.service_name }}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/chatqna-default: "true"
        io.kompose.service: {{ .Values.global.amdllm.service_name }}
    spec:
      containers:
        - env:
            {{- if .Values.global.amdllm.env }}
            {{- range .Values.global.amdllm.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
            - name: {{ .Values.global.amdllm.tei_service.env_var_name }}
              value: "http://{{ .Values.global.amdllm.tei_service.name }}.{{ .Values.global.amdllm.namespace }}.svc.cluster.local:{{ .Values.global.amdllm.tei_service.port }}"
            {{- if .Values.global.amdllm.runtime_envs }}
            {{- range .Values.global.amdllm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.amdllm.image }}
          name: {{ .Values.global.amdllm.service_name }}-server
          ports:
            - containerPort: {{ .Values.global.amdllm.container_port }}
              protocol: TCP
          volumeMounts:
            {{- if .Values.global.amdllm.volume }}
            {{- range .Values.global.amdllm.volume }}
            - name: {{ .name }}
              mountPath: {{ .path }}
            {{- end }}
            {{- end }}
      restartPolicy: Always
      volumes:
        {{- if .Values.global.amdllm.volume }}
        {{- range .Values.global.amdllm.volume }}
        - name: {{ .name }}
          emptyDir: {}
        {{- end }}
        {{- end }}
